location             = "westeurope"
resource_group_name  = "tf-state-rg"
storage_account_name = "tfstatedan"
index_document       = "index.html"
source_content       = "<h1> This site was deployed by Terraform</h1>"